---

- import_tasks: unattended_upgrades.yml

- import_tasks: login_info.yml

- name: Install useful packages
  ansible.builtin.apt:
    name:
      - atop
      - htop
      - lsof
      - nano
      - net-tools
      - nmap
      - vim
    state: present
