---
{% raw %}
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Configure Unattended-Upgrade
  ansible.builtin.lineinfile:
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    regexp: "^APT::Periodic::Unattended-Upgrade"
    line: "APT::Periodic::Unattended-Upgrade \"{{ base_install_updates_automatically | bool | ternary(1, 0) }}\";"
{% endraw -%}
