---

roles:
  - name: geerlingguy.postgresql
    version: "2.2.1"

  - name: geerlingguy.nginx
    version: "2.8.0"

  - name: geerlingguy.nodejs
    version: "5.1.1"

  - name: tmiller02.yarn
    version: "0.1.0"
