---

roles:
  - name: tmiller02.geckodriver
    version: "0.1.0"

  - name: geerlingguy.postgresql
    version: "3.4.2"

  - name: geerlingguy.nginx
    version: "3.1.4"

  - name: geerlingguy.nodejs
    version: "6.1.1"
