---

roles:
  - name: geerlingguy.postgresql
    version: "3.1.1"

  - name: geerlingguy.nginx
    version: "3.1.0"

  - name: geerlingguy.nodejs
    version: "6.0.0"

  - name: tmiller02.yarn
    version: "0.1.0"
