---
{% raw %}
- name: create a directory for storing certificate signing requests
  file:
    state: directory
    path: "/etc/ssl/csr/"
    owner: root
    group: root

- name: generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{ ssl_private_key_dest }}"
    backup: true
  notify: "updated ssl"

- name: generate an OpenSSL certificate signing request
  openssl_csr:
    path: "{{ ssl_csr_path }}"
    privatekey_path: "{{ ssl_private_key_dest }}"
    common_name: "{{ ssl_common_name }}"
    use_common_name_for_san: yes
    key_usage:
      - nonRepudiation
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth

- name: generate a self-signed OpenSSL certificate
  openssl_certificate:
    path: "{{ ssl_certificate_dest }}"
    privatekey_path: "{{ ssl_private_key_dest }}"
    csr_path: "{{ ssl_csr_path }}"
    provider: selfsigned
    selfsigned_not_after: "+365d"
  notify: "updated ssl"
{% endraw %}
