---
{% raw %}
deploy_check_display_confirmation_prompts: false

base_show_production_login_warning: false
base_install_updates_automatically: true

backend_server_name: "localhost"

frontend_server_name: "localhost"
frontend_app_backend_url: "https://{{ backend_server_name }}:4000"

database_password: "$DATABASE PASSWORD$"

ufw_firewall_state: "disabled"
ufw_firewall_database_allow_from_ip:
 - 172.17.177.21

ufw_firewall_additional_rules:
  # Ensure the django dev server is accessible from any address
  - port: "4001"
    proto: "tcp"
    rule: "allow"
    from_ip: ["any"]
    when: "{{ 'backend' in group_names }}"
  # Ensure the postgres server is accessible from any address. Don't set this
  # in a production environment!
  - port: "5432"
    proto: "tcp"
    rule: "allow"
    from_ip: ["any"]
    when: "{{ 'database' in group_names }}"
{% endraw %}
ssl_provider: 'selfsigned'
