---
{% raw %}
deploy_check_display_confirmation_prompts: false

base_show_production_login_warning: false
base_install_updates_automatically: true

backend_server_name: "localhost"

frontend_server_name: "localhost"
frontend_app_backend_url: "https://{{ backend_server_name }}:4000"

database_password: "$DATABASE PASSWORD$"

firewalld_zones:
  - name: backend
    ip_addresses:
     - 172.17.177.21

firewalld_additional_rules:
  # Ensure the django dev server is accessible from any address
  - port: "8000/tcp"
    state: "enabled"
    zone: "public"
    when: "{{ 'backend' in group_names }}"
  # Ensure the postgres server is accessible from any address. Don't set this
  # in a production environment!
  - port: "5432/tcp"
    state: "enabled"
    zone: "public"
    when: "{{ 'database' in group_names }}"
{% endraw %}
ssl_provider: 'selfsigned'
