---
{% raw %}
deploy_check_display_confirmation_prompts: false

base_show_production_login_warning: false

backend_server_name: "localhost"

frontend_server_name: "localhost"
frontend_app_backend_url: "https://{{ backend_server_name }}:4000"

database_password: "$DATABASE PASSWORD$"

configure_ufw_firewall: false
ufw_firewall_rules: []

ssl_provider: 'selfsigned'
{% endraw %}
