---

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  # Ensure the dev postgres server is accessible from any address (to allow access
  # from tools such as PyCharm of pgAdmin). Don't set this in a production environment!
  - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
