---
{% raw %}
- name: Add django clearsessions cron job
  ansible.builtin.cron:
    name: django clearsessions
    minute: "0"
    hour: "10"
    user: "{{ backend_app_user }}"
    job: ". ~/.venvrc && python manage.py clearsessions"
{% endraw -%}
