---

- name: Add the mozilla ppa
  ansible.builtin.apt_repository:
    repo: "ppa:mozillateam/ppa"

- name: Install packages used with selenium and X11 forwarding
  ansible.builtin.apt:
    name:
      - firefox-esr
      - xauth
      - x11-apps
    state: present
