---

- name: Add the mozilla ppa
  ansible.builtin.apt_repository:
    repo: "ppa:mozillateam/ppa"

- name: Install packages used with selenium
  ansible.builtin.apt:
    name:
      - firefox-esr
      - firefox-esr-geckodriver
    state: present
