---
{% raw %}
- name: Run database migrations
  become: true
  become_user: "{{ backend_app_user }}"
  run_once: true
  community.general.django_manage:
    command: "migrate"
    app_path: "{{ backend_app_deploy_helper.current_path }}"
    virtualenv: "{{ backend_app_deploy_helper.current_path }}/.venv/"
  register:
    django_manage_migrate

- name: Display migrate output
  run_once: true
  ansible.builtin.debug:
    msg: "{{ django_manage_migrate.out }}"
{% endraw -%}
