---
{% raw %}
- name: Add systemd unit file
  ansible.builtin.template:
    src: systemd_service.j2
    dest: "/etc/systemd/system/{{ backend_app_systemd_unit_name }}.service"

- name: Enable and restart the systemd unit
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ backend_app_systemd_unit_name }}"
    enabled: true
    state: restarted
{% endraw -%}
