---
{% raw %}
- name: Create the backend app group
  ansible.builtin.group:
    name: "{{ backend_app_group }}"
    system: true

- name: Create the backend app user
  ansible.builtin.user:
    name: "{{ backend_app_user }}"
    group: "{{ backend_app_group }}"
{% endraw -%}
