---
{% raw %}
- name: install python packages and build dependencies
  become: true
  apt:
    name:
      - libpq-dev
      - python3-dev
      - python3-venv
      - python3-pip
      - watchman
    state: present

- name: set up virtualenv in new release path
  become: true
  become_user: "{{ backend_app_user }}"
  pip:
    virtualenv: "{{ backend_app_virtualenv_dir }}"
    virtualenv_command: /usr/bin/python3.10 -m venv
    name:
      - pip==21.3.1
      - pip-tools==6.5.0
      - setuptools==60.7.1
      - wheel==0.37.1

- name: install requirements using pip-sync
  become: true
  become_user: "{{ backend_app_user }}"
  # Use legacy pip resolver, work around issue https://github.com/pypa/pip/issues/9243
  # where the new resolver may try to install a sub-dependency version that differs
  # from the pinned version in requirements.txt
  command: "{{ backend_app_virtualenv_dir }}/bin/pip-sync --pip-args='--use-deprecated=legacy-resolver'"
  args:
    chdir: "{{ backend_app_deploy_helper.new_release_path }}"
  changed_when: true
{% endraw %}
