---
{% raw %}
- name: install python packages
  become: true
  apt:
    name:
      - python3-dev
      - python3-venv
      - python3-pip
    state: present

- name: set up virtualenv in new release path
  become: true
  become_user: "{{ backend_app_user }}"
  pip:
    virtualenv: "{{ backend_app_virtualenv_dir }}"
    virtualenv_command: /usr/bin/python3.8 -m venv
    name:
      - pip==20.2.4
      - pip-tools==5.3.1
      - setuptools==50.3.2

- name: install requirements using pip-sync
  become: true
  become_user: "{{ backend_app_user }}"
  command: "{{ backend_app_virtualenv_dir }}/bin/pip-sync"
  args:
    chdir: "{{ backend_app_deploy_helper.new_release_path }}"
  changed_when: true
{% endraw %}
