# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vagrant.plugins = ["vagrant-vbguest"]
  config.vm.box = "centos/7"
  config.vm.box_check_update = true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vbguest.auto_update = true

  config.vm.define "node1", primary: true do |machine|
    machine.vm.synced_folder(
      "./backend_app",
      "/opt/{{ cookiecutter.project_slug }}_backend",
      type: "virtualbox",
      mount_options: ["uid=1234", "gid=1234"]
    )
    machine.vm.network "private_network", ip: "172.17.177.21"
    machine.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "{{ cookiecutter.project_slug }}_node1"
    end
  end

  config.vm.define "controller" do |machine|
    machine.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    machine.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "{{ cookiecutter.project_slug }}_controller"
      virtualbox.memory = 512
    end
    machine.vm.provision "ansible_local" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook.yml"
      ansible.provisioning_path = "/vagrant/provisioning"
      ansible.config_file = "ansible-vagrant.cfg"
      ansible.install_mode = "pip_args_only"
      ansible.pip_install_cmd = "sudo yum install -y epel-release && sudo yum install -y python2-pip"
      ansible.pip_args = "-r /vagrant/provisioning/requirements.txt"
      ansible.galaxy_role_file = "requirements.yml"
      ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --force"
      ansible.verbose = false
      ansible.limit = "all"
      ansible.inventory_path = "environments/dev/inventory.yml"
    end
  end

end
