---
{% raw %}
- name: Install npm packages
  community.general.npm:
    path: "{{ playbook_dir }}/../frontend_app/"
    ci: true

- name: Build the frontend app bundle
  ansible.builtin.command: npm run build
  args:
    chdir: "{{ playbook_dir }}/../frontend_app/"
  environment:
    VITE_BACKEND_URL: "{{ frontend_app_backend_url }}"
  changed_when: true

# Note that this doesn't fail the playbook if vulnerable packages are found.
# This only displays the report in the ansible output, so we don't cause any
# deployment to fail unexpectedly.
- name: Run npm audit
  ansible.builtin.command: npm audit
  args:
    chdir: "{{ playbook_dir }}/../frontend_app/"
  ignore_errors: true
  changed_when: true
{% endraw -%}
