---
{% raw %}
- name: install npm packages
  command: npm clean-install
  args:
    chdir: "{{ playbook_dir }}/../frontend_app/"

- name: build the frontend app bundle
  command: npm run build
  args:
    chdir: "{{ playbook_dir }}/../frontend_app/"
  environment:
    REACT_APP_BACKEND_URL: "{{ frontend_app_backend_url }}"

# Note that this doesn't fail the playbook if vulnerable packages are found.
# This only displays the report in the ansible output so we don't cause any
# deployment to fail unexpectedly.
- name: run npm audit
  command: npm audit
  args:
    chdir: "{{ playbook_dir }}/../frontend_app/"
  ignore_errors: true
  changed_when: false
{% endraw %}
